#ifndef __RISC_V_FT_H_UAPI__
#define __RISC_V_FT_H_UAPI__

#include <linux/ioctl.h>

#define RISC_V_IOCTL_MAGIC 'T'

#define RISC_V_RESET_CPUS    _IO(RISC_V_IOCTL_MAGIC, 1)
#define RISC_V_RELEASE_RESET _IO(RISC_V_IOCTL_MAGIC, 2)
#define RISC_V_DISABLE_CLKS  _IO(RISC_V_IOCTL_MAGIC, 3)
#define RISC_V_ENABLE_CLKS   _IO(RISC_V_IOCTL_MAGIC, 4)
#define RISC_V_BREAK_CPU     _IO(RISC_V_IOCTL_MAGIC, 5)
#define RISC_V_RESET_SINGLE  _IO(RISC_V_IOCTL_MAGIC, 6)
#define RISC_V_SET_FIRMWARE_TYPE  _IO(RISC_V_IOCTL_MAGIC, 7)

#endif //__RISC_V_FT_H_UAPI__
